# Rustfmt configuration file

# Set the maximum line width
max_width = 80

# Use 4 spaces for indentation
tab_spaces = 4

# Use the default set of rules
# Uncomment the following line to enable custom rules
# custom_rules = true

brace_style = "PreferSameLine"
enum_discrim_align_threshold = 30