[package]
name = "nexus-example"
version.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["dylib"]

[lints]
workspace = true

[dependencies]
nexus-api.workspace = true
tracing.workspace = true
nexus-api-macros.workspace = true
