[package]
name = "nexus-api"
version.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
tracing.workspace = true
async-trait.workspace = true
tracing-subscriber.workspace = true
